{
  "swagger" : "2.0",
  "info" : {
    "description" : "Book-A-Meal is an application that allows customers to make food orders and helps the food\nvendor know what the customers want to eat\n",
    "version" : "1",
    "title" : "Book A Meal API"
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/ozimos7/Book_A_Meal-API/1",
  "schemes" : [ "https" ],
  "paths" : {
    "/api/v1/auth/signup" : {
      "post" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "Create a new user",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/SignUp"
          },
          "x-examples" : {
            "application/json" : " {\r\n\"firstName\":\"Tovieye\", \r\n\"lastName\":\"Ozi\", \r\n\"email\":\"ozimos83@yahoo.com\", \r\n\"password\":\"test\"\r\n, \r\n\"confirmPassword\":\"test\"\r\n}"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Return user details as saved on database and success message",
            "schema" : {
              "$ref" : "#/definitions/SignUp"
            }
          },
          "400" : {
            "description" : "Invalid input"
          }
        }
      }
    },
    "/api/v1/auth/login" : {
      "post" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "Log a user in",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/Login"
          },
          "x-examples" : {
            "application/json" : "{\r\n\"email\":\"ozimos83@yahoo.com\",\r\n\"password\":\"test\"\r\n}"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Return user details as saved on database and success message",
            "schema" : {
              "$ref" : "#/definitions/SignUp"
            }
          },
          "404" : {
            "description" : "Invalid input"
          }
        }
      }
    },
    "/api/v1/meals" : {
      "get" : {
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Return all meals details as saved on database"
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      },
      "post" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "Add a new meal",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/Meals"
          },
          "x-examples" : {
            "application/json" : "{\r\n\"title\":\"amala and ewedu\",\r\n\"description\":\"satisfying\",\r\n\"price\":\"2000\",\r\n\"imageUrl\":\"https://cdn.pixabay.com/photo/2017/11/23/13/50/pumpkin-soup-2972858_960_720.jpg\",\r\n\"userId\":\"67217a96-9fa9-451b-8244-738f9ba8f63b\"\r\n}"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Return meal details as saved on database",
            "schema" : {
              "$ref" : "#/definitions/Meals"
            }
          },
          "400" : {
            "description" : "Invalid input"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      }
    },
    "/api/v1/meals/{mealId}" : {
      "put" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Meals"
          },
          "x-examples" : {
            "application/json" : "{\r\n\"title\":\"chicken wings with chips\",\r\n\"description\":\"exotic\"\r\n}"
          }
        }, {
          "name" : "mealId",
          "in" : "path",
          "description" : "Meal Id",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Return meal details as updated on database"
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      },
      "delete" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "mealId",
          "in" : "path",
          "description" : "Meal Id",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Return meal details as saved on database"
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      }
    },
    "/api/v1/orders/{orderId}" : {
      "put" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Orders"
          },
          "x-examples" : {
            "application/json" : "{\r\n\"meals\":[\"084a7e7c-ef72-45cd-8998-727e56af2759\", \"efe1ed43-6169-4b9c-bd2d-fcdea22f2be4\"]\r\n}"
          }
        }, {
          "name" : "orderId",
          "in" : "path",
          "description" : "Meal Id",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Return order details as saved on database"
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      }
    },
    "/api/v1/orders" : {
      "get" : {
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Return all order details as saved on database",
            "schema" : {
              "$ref" : "#/definitions/OrdersGetResponse"
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      },
      "post" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/Orders"
          },
          "x-examples" : {
            "application/json" : "{\r\n\"meals\" :[{\"id\": \"084a7e7c-ef72-45cd-8998-727e56af2759\", \"quantity\": \"1\"}]\r\n}"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Return order details as saved on database",
            "schema" : {
              "$ref" : "#/definitions/OrdersPostResponse"
            }
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      }
    },
    "/api/v1/menu" : {
      "get" : {
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Return all order details as saved on database"
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      },
      "post" : {
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/Menu"
          },
          "x-examples" : {
            "application/json" : "{\r\n\"description\":\"Wednesday's Menu\",\r\n\"meals\":[\"084a7e7c-ef72-45cd-8998-727e56af2759\", \"efe1ed43-6169-4b9c-bd2d-fcdea22f2be4\", \"74011cce-299a-4a9d-84b2-55398748d360\"]\r\n}"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Return order details as saved on database"
          },
          "400" : {
            "description" : "Bad Request"
          },
          "404" : {
            "description" : "No records available"
          }
        },
        "security" : [ {
          "jwt" : [ ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "jwt" : {
      "type" : "apiKey",
      "name" : "authorization",
      "in" : "header"
    }
  },
  "definitions" : {
    "Meals" : {
      "type" : "object",
      "properties" : {
        "title" : {
          "type" : "string"
        },
        "description" : {
          "type" : "string"
        },
        "price" : {
          "type" : "string"
        },
        "imageUrl" : {
          "type" : "string"
        },
        "userId" : {
          "type" : "string",
          "format" : "uuidv4"
        }
      },
      "example" : {
        "price" : "price",
        "imageUrl" : "imageUrl",
        "description" : "description",
        "title" : "title",
        "userId" : "userId"
      }
    },
    "Orders" : {
      "type" : "object",
      "properties" : {
        "meals" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Orders_meals"
          }
        }
      },
      "example" : {
        "meals" : [ {
          "id" : "443b76e7-b152-4937-890e-492c842b45a8",
          "quantity" : "1"
        }, {
          "id" : "443b76e7-b152-4937-890e-492c842b45a8",
          "quantity" : "1"
        } ]
      }
    },
    "OrdersGetResponse" : {
      "type" : "object",
      "properties" : {
        "meals" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Orders_meals"
          }
        }
      },
      "example" : {
        "data" : [ {
          "id" : "b7f4b44a-052a-457c-8422-327e106ddbed",
          "createdAt" : "2018-06-12T08:29:07.670Z",
          "updatedAt" : "2018-06-12T08:29:07.670Z",
          "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
          "Meals" : [ {
            "id" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
            "title" : "Starch and Edikangkong",
            "description" : "swallow with vegetable soup",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 2
            }
          }, {
            "id" : "adb53a5a-06c7-4067-8062-c71a7ac5484e",
            "title" : "Beef with Rice",
            "description" : "plain rice with ground beef",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 3
            }
          } ]
        }, {
          "id" : "b8c05c01-7ed0-45eb-b3b4-e9ff52ffe17c",
          "createdAt" : "2018-06-12T08:31:15.569Z",
          "updatedAt" : "2018-06-12T08:31:15.569Z",
          "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
          "Meals" : [ {
            "id" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
            "title" : "Starch and Edikangkong",
            "description" : "swallow with vegetable soup",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 2
            }
          }, {
            "id" : "adb53a5a-06c7-4067-8062-c71a7ac5484e",
            "title" : "Beef with Rice",
            "description" : "plain rice with ground beef",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 3
            }
          } ]
        }, {
          "id" : "98aa2afd-f14f-4fee-999f-f496518d81d6",
          "createdAt" : "2018-06-12T08:31:47.811Z",
          "updatedAt" : "2018-06-12T08:31:47.811Z",
          "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
          "Meals" : [ {
            "id" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
            "title" : "Starch and Edikangkong",
            "description" : "swallow with vegetable soup",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 2
            }
          }, {
            "id" : "adb53a5a-06c7-4067-8062-c71a7ac5484e",
            "title" : "Beef with Rice",
            "description" : "plain rice with ground beef",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 3
            }
          } ]
        }, {
          "id" : "96baddec-af73-456c-8c2b-c73c0dd67a78",
          "createdAt" : "2018-06-12T12:40:00.781Z",
          "updatedAt" : "2018-06-12T12:40:00.781Z",
          "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
          "Meals" : [ {
            "id" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
            "title" : "Starch and Edikangkong",
            "description" : "swallow with vegetable soup",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 2
            }
          }, {
            "id" : "a30194b2-7925-48bf-99f2-5847042f34fd",
            "title" : "Amala and Ewedu",
            "description" : "allow",
            "price" : 3000,
            "MealOrders" : {
              "quantity" : 1
            }
          } ]
        }, {
          "id" : "2c7ba6d8-643b-4e0e-a182-c7edfab6fc0d",
          "createdAt" : "2018-06-12T12:40:15.696Z",
          "updatedAt" : "2018-06-12T12:40:15.696Z",
          "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
          "Meals" : [ {
            "id" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
            "title" : "Starch and Edikangkong",
            "description" : "swallow with vegetable soup",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 2
            }
          }, {
            "id" : "a30194b2-7925-48bf-99f2-5847042f34fd",
            "title" : "Amala and Ewedu",
            "description" : "allow",
            "price" : 3000,
            "MealOrders" : {
              "quantity" : 1
            }
          } ]
        }, {
          "id" : "f2e1da5f-d52c-4434-bd2f-39fc62beaec4",
          "createdAt" : "2018-06-12T12:41:30.652Z",
          "updatedAt" : "2018-06-12T12:41:30.652Z",
          "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
          "Meals" : [ {
            "id" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
            "title" : "Starch and Edikangkong",
            "description" : "swallow with vegetable soup",
            "price" : 2500,
            "MealOrders" : {
              "quantity" : 2
            }
          }, {
            "id" : "a30194b2-7925-48bf-99f2-5847042f34fd",
            "title" : "Amala and Ewedu",
            "description" : "allow",
            "price" : 3000,
            "MealOrders" : {
              "quantity" : 1
            }
          }, {
            "id" : "58355807-693d-435f-8284-c63f52563165",
            "title" : "Delicious Spaghetti and Tomato Sauce",
            "description" : "Alluring",
            "price" : 3200,
            "MealOrders" : {
              "quantity" : 2
            }
          } ]
        } ]
      }
    },
    "OrdersPostResponse" : {
      "type" : "object",
      "properties" : {
        "meals" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Orders_meals"
          }
        }
      },
      "example" : {
        "data" : {
          "id" : "f2e1da5f-d52c-4434-bd2f-39fc62beaec4",
          "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
          "updatedAt" : "2018-06-12T12:41:30.652Z",
          "createdAt" : "2018-06-12T12:41:30.652Z",
          "Meals" : [ {
            "id" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
            "title" : "Starch and Edikangkong",
            "description" : "swallow with vegetable soup",
            "imageUrl" : "https://res.cloudinary.com/tovieyeozim/image/upload/v1528740846/awlipmzzr3jn63ne9jlf.jpg",
            "price" : 2500,
            "createdAt" : "2018-06-10T17:11:38.276Z",
            "updatedAt" : "2018-06-11T18:24:48.023Z",
            "deletedAt" : null,
            "userId" : "6d15d03a-93f2-4b82-a707-9e2af07c0d91",
            "MealOrders" : {
              "quantity" : 2,
              "createdAt" : "2018-06-12T12:41:30.679Z",
              "updatedAt" : "2018-06-12T12:41:30.679Z",
              "mealId" : "6aaa93e3-5a68-45a1-861b-d13c0b0cb967",
              "orderId" : "f2e1da5f-d52c-4434-bd2f-39fc62beaec4"
            }
          }, {
            "id" : "a30194b2-7925-48bf-99f2-5847042f34fd",
            "title" : "Amala and Ewedu",
            "description" : "allow",
            "imageUrl" : "https://res.cloudinary.com/tovieyeozim/image/upload/v1528741951/yrj7mcoon9maexboruvl.jpg",
            "price" : 3000,
            "createdAt" : "2018-06-05T20:40:37.259Z",
            "updatedAt" : "2018-06-11T18:32:40.051Z",
            "deletedAt" : null,
            "userId" : "db5e4fa9-d4df-4352-a2e4-bc57f6b68e9b",
            "MealOrders" : {
              "quantity" : 1,
              "createdAt" : "2018-06-12T12:41:30.687Z",
              "updatedAt" : "2018-06-12T12:41:30.687Z",
              "mealId" : "a30194b2-7925-48bf-99f2-5847042f34fd",
              "orderId" : "f2e1da5f-d52c-4434-bd2f-39fc62beaec4"
            }
          }, {
            "id" : "58355807-693d-435f-8284-c63f52563165",
            "title" : "Delicious Spaghetti and Tomato Sauce",
            "description" : "Alluring",
            "imageUrl" : "https://res.cloudinary.com/tovieyeozim/image/upload/v1528742169/hb9tdneoqtyl35cv5q36.jpg",
            "price" : 3200,
            "createdAt" : "2018-06-11T18:37:08.540Z",
            "updatedAt" : "2018-06-11T18:37:08.540Z",
            "deletedAt" : null,
            "userId" : "6d15d03a-93f2-4b82-a707-9e2af07c0d91",
            "MealOrders" : {
              "quantity" : 2,
              "createdAt" : "2018-06-12T12:41:30.692Z",
              "updatedAt" : "2018-06-12T12:41:30.692Z",
              "mealId" : "58355807-693d-435f-8284-c63f52563165",
              "orderId" : "f2e1da5f-d52c-4434-bd2f-39fc62beaec4"
            }
          } ],
          "mealList" : [ "6aaa93e3-5a68-45a1-861b-d13c0b0cb967", "a30194b2-7925-48bf-99f2-5847042f34fd", "58355807-693d-435f-8284-c63f52563165" ],
          "quantityList" : [ 2, 1, 2 ]
        }
      }
    },
    "Menu" : {
      "type" : "object",
      "properties" : {
        "description" : {
          "type" : "string"
        },
        "meals" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "format" : "uuidv4"
          }
        }
      },
      "example" : {
        "description" : "Thursday Menu",
        "meals" : [ "443b76e7-b152-4937-890e-492c842b45a8", "443b76e7-b152-4937-890e-492c842b45a8" ]
      }
    },
    "SignUp" : {
      "type" : "object",
      "properties" : {
        "firstName" : {
          "type" : "string"
        },
        "lastName" : {
          "type" : "string"
        },
        "email" : {
          "type" : "string",
          "format" : "email"
        },
        "password" : {
          "type" : "string"
        },
        "confirmPassword" : {
          "type" : "string"
        },
        "isCaterer" : {
          "type" : "boolean"
        }
      },
      "example" : {
        "firstName" : "firstName",
        "lastName" : "lastName",
        "password" : "password",
        "isCaterer" : true,
        "confirmPassword" : "confirmPassword",
        "email" : "email"
      }
    },
    "Login" : {
      "type" : "object",
      "properties" : {
        "email" : {
          "type" : "string",
          "format" : "email"
        },
        "password" : {
          "type" : "string"
        }
      },
      "example" : {
        "password" : "password",
        "email" : "email"
      }
    },
    "Orders_meals" : {
      "properties" : {
        "id" : {
          "type" : "string",
          "format" : "uuidv4"
        },
        "quantity" : {
          "type" : "string"
        }
      }
    }
  }
}